apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: alertmanager
spec:
  type: NodePort
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 30903
  selector:
    app: alertmanager
