apiVersion: v1
kind: ConfigMap
metadata:
  namespace: php-app
  name: php-config
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    listen.owner = www-data
    listen.group = www-data
    pm = dynamic
    pm.max_children = 50
    pm.start_servers = 5
    pm.min_spare_servers = 5
    pm.max_spare_servers = 35
    pm.max_requests = 500

    ; Enhanced logging
    access.log = /var/log/php-fpm-access.log
    access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"

    slowlog = /var/log/php-fpm-slow.log
    request_slowlog_timeout = 5s
    catch_workers_output = yes
    php_admin_value[error_log] = /var/log/php-fpm-error.log
    php_admin_flag[log_errors] = on
    php_value[session.save_handler] = files
    php_value[session.save_path] = /var/lib/php/sessions
    php_value[soap.wsdl_cache_dir] = /var/lib/php/wsdlcache
