apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: loki-config
data:
  loki.yml: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      wal:
        enabled: false

    schema_config:
      configs:
      - from: 2025-07-12
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      allow_structured_metadata: false  # Critical addition to fix the error
