apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: php-app
  name: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
      - name: php-fpm
        image: php:8.2-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: php-config
          mountPath: /usr/local/etc/php-fpm.d/www.conf
          subPath: www.conf
        - name: app-code
          mountPath: /var/www/html
        - name: php-logs
          mountPath: /var/log/php-fpm
        - name: php-sessions
          mountPath: /var/lib/php/sessions
        - name: php-wsdlcache
          mountPath: /var/lib/php/wsdlcache

      - name: nginx
        image: nginx:1.23  # Use the lua-enabled version
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: app-code
          mountPath: /var/www/html
        - name: nginx-logs
          mountPath: /var/log/nginx

      volumes:
      - name: php-config
        configMap:
          name: php-config
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: app-code
        configMap:
          name: app-code
      - name: php-logs
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      - name: php-sessions
        emptyDir: {}
      - name: php-wsdlcache
        emptyDir: {}
