---
apiVersion: v1
kind: Namespace
metadata:
  name: php-app
  labels:
    name: php-app
  annotations:
    env: "prod"  # Production environment for the PHP application
    purpose: "Production environment for PHP-FPM + NGINX deployment"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
  annotations:
    env: "observability"  # Observability (monitoring/logging) environment
    purpose: "Hosts monitoring tools (e.g., Prometheus, Grafana)"
