apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
