apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    scrape_configs:
      - job_name: 'nginx-status'
        metrics_path: /nginx_status
        static_configs:
          - targets: ['192.168.56.10:30080']

      - job_name: 'nginx-exporter'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['nginx-exporter.monitoring.svc.cluster.local:9113']

  rules.yml: |+
    groups:
    - name: Nginx-Status
      rules:
      
      - alert: Nginx-Down
        expr: nginx_up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "NGINX exporter is down (instance {{ $labels.instance }})"
          description: "The NGINX Prometheus exporter has been unreachable for 2 minutes. Metrics collection has stopped."

      - alert: NginxHighActiveConnections
        expr: |
          nginx_connections_active > 100
          or
          rate(nginx_connections_accepted[5m]) > 500
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High active connections (instance {{ $labels.instance }})"
          description: "NGINX has {{ $value }} active connections (threshold: 100). Current accept rate: {{ rate(nginx_connections_accepted[5m]) | humanize }} connections/s."      

      - alert: NginxConnectionHandlingErrors
        expr: |
          (nginx_connections_accepted - nginx_connections_handled) > (nginx_connections_accepted * 0.05)
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "NGINX connection handling errors (instance {{ $labels.instance }})"
          description: "{{ (nginx_connections_accepted - nginx_connections_handled) | humanize }} connections were not properly handled ({{ printf \"%.1f\" ( (nginx_connections_accepted - nginx_connections_handled) / nginx_connections_accepted * 100 ) }}% error rate)."

      - alert: NginxRequestBacklog
        expr: |
          nginx_connections_waiting > 50
          and
          nginx_connections_writing < 5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "NGINX request backlog (instance {{ $labels.instance }})"
          description: "High waiting connections ({{ $value }}) with low writing activity. Possible backend slowdown."    

      - alert: NginxTrafficSpike
        expr: |
          rate(nginx_http_requests_total[1m]) > (avg(rate(nginx_http_requests_total[1h])) * 3
          and
          rate(nginx_http_requests_total[1m]) > 1000
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Abnormal traffic spike (instance {{ $labels.instance }})"
          description: "Current request rate: {{ $value | humanize }} req/s (3x higher than 1h average)."

      - alert: NginxStalledConnections
        expr: |
          nginx_connections_reading > avg(nginx_connections_reading[1h]) * 5
          and
          nginx_connections_reading > 10
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "NGINX stalled connections (instance {{ $labels.instance }})"
          description: "{{ $value }} connections stuck in reading state (5x higher than usual)."










      
