apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: prometheus
  externalTrafficPolicy: Local
  ports:
  - name: web
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30909
